options:
  merge-default-rules: false
rules:
  border-zero:
    - 2
    -
      convention: 0
  brace-style:
    - 2
    -
      style: stroustrup
      allow-single-line: false
  class-name-format: 2
  clean-import-paths: 2
  empty-args: 2
  empty-line-between-blocks:
    - 2
    -
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  force-element-nesting: 2
  function-name-format: 2
  hex-length: 2
  hex-notation: 2
  id-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: snakecase
  indentation: 2
  leading-zero:
    - 2
    -
      include: true
  mixin-name-format: 2
  mixins-before-declarations: 2
  nesting-depth:
    - 1
    -
      max-depth: 4
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-trailing-zero: 2
  no-transition-all: 1
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format: 2
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 1
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format: 2
  zero-unit: 2